AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2

Rails:
  Enabled: true
  
Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/SymbolArray:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Layout/AlignParameters:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
