AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/EmtpyLinesAroundBlockBody:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
