language: ruby
dist: trusty
sudo: required
cache: bundler
rvm:
  - 2.3.6

addons:
  mariadb: '10.1'
  
services:
  - mysql

before_install:
  - sudo apt-get install software-properties-common
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
  - sudo add-apt-repository -y 'deb [arch=amd64,i386,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.1/ubuntu trusty main'
  - sudo add-apt-repository -y ppa:builds/sphinxsearch-rel22
  - sudo apt-get -qq update
  - sudo apt-get install -y libmariadbclient-dev
  - sudo apt-get install -y sphinxsearch

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/lilsis.yml.sample config/lilsis.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - mysql -e 'CREATE DATABASE littlesis_test;'

script:
  - RAILS_ENV=test bundle exec rake db:structure:load
  - RAILS_ENV=test bundle exec rake db:seed
  - RAILS_ENV=test COVERAGE=true bundle exec rspec
