language: ruby
cache: bundler
rvm:
  - 2.3.3

addons:
  mariadb: '10.1'
  
services:
  - mysql

before_install:
  - sudo apt-get install software-properties-common
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
  - sudo add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.1/ubuntu trusty main'
  - sudo apt-get install libmariadbclient-dev

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/lilsis.yml.sample config/lilsis.yml
  - mysql -e 'CREATE DATABASE littlesis_test;'

script:
  - RAILS_ENV=test bundle exec rake db:structure:load
  - RAILS_ENV=test bundle exec rake db:seed
  - RAILS_ENV=test bundle exec rspec
