---
common:
  ignore:
    - last_user_id
    - delta
    - id
    - created_at
    - notes
entity:
  ignore: 
    - is_deleted
    - merged_id
    - is_current
    - link_count
  fields:
    aliases: 'aliases.map(&:name)'
    types: 'types'
    extensions: 'extensions_with_attributes'
relationship:
  ignore:
    - amount2
    - is_gte
extensionrecord:
  ignore:
    - entity_id
  fields:
    display_name: 'extension_definition.display_name'
    name: 'extension_definition.name'
    
