---
-
  name: fossil-fuel
  description: "Oil, gas, and coal firms"
  id: 1
-
  name: real-estate
  description: "The real estate industry"
  id: 2
-
  name: finance
  description: "Banks, hedge funds and private equity firms"
  id: 3
-
  name: fracking
  description: "People and companies involved in fracking"
  id: 4
